const appname = "bonSAi Seller App",
    login = "Login",
    loginHint = "Login to your account",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    oldPassword = "Old Password",
    confirmPassword = "Confirm Password",
    newPassword = "New Password",
    forgotPassword = "Forgot Password?",
    anyProblem = "In case of any difficulty, contact administration",
    credit = "@HD";

const emailHint = "bonsaiseller@gmail.com", passwordHint = " *** *** *** ";

const dashboard = "Dashboard",
    orders = "Orders",
    products = "Products",
    settings = "Settings",
    shopSettings = "Shop Settings",
    rating = "Rating",
    editProfile = "Edit Profile",
    changeImage = "Change Image",
    name = "User Name",
    description = "Description",
    shopDescription = "Enter Your Shop Description",
    website = "Shop Website",
    shopMobileNumber = "+880 1754552486",
    shopAddress = "Address",
    shopWebsite = "https//:bonsaiseller",
    shopName = "Shop Name",
    logout = "Logout",
    loggedIn = "Login successfull",
    totalSales = "Total sale",
    messages = "Messages",
    logOut = "Logout",
    popular_products = "Popular products",
    unpaid = "Unpaid",
    chatscreen = "Chat";

const featured = "Featured", edit = "Edit", delete = "Delete", save = "Save";
